// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/d0lim/turnstile/internal/ent/predicate"
	"github.com/d0lim/turnstile/internal/ent/useroauthprovider"
)

// UserOauthProviderQuery is the builder for querying UserOauthProvider entities.
type UserOauthProviderQuery struct {
	config
	ctx        *QueryContext
	order      []useroauthprovider.OrderOption
	inters     []Interceptor
	predicates []predicate.UserOauthProvider
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserOauthProviderQuery builder.
func (uopq *UserOauthProviderQuery) Where(ps ...predicate.UserOauthProvider) *UserOauthProviderQuery {
	uopq.predicates = append(uopq.predicates, ps...)
	return uopq
}

// Limit the number of records to be returned by this query.
func (uopq *UserOauthProviderQuery) Limit(limit int) *UserOauthProviderQuery {
	uopq.ctx.Limit = &limit
	return uopq
}

// Offset to start from.
func (uopq *UserOauthProviderQuery) Offset(offset int) *UserOauthProviderQuery {
	uopq.ctx.Offset = &offset
	return uopq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uopq *UserOauthProviderQuery) Unique(unique bool) *UserOauthProviderQuery {
	uopq.ctx.Unique = &unique
	return uopq
}

// Order specifies how the records should be ordered.
func (uopq *UserOauthProviderQuery) Order(o ...useroauthprovider.OrderOption) *UserOauthProviderQuery {
	uopq.order = append(uopq.order, o...)
	return uopq
}

// First returns the first UserOauthProvider entity from the query.
// Returns a *NotFoundError when no UserOauthProvider was found.
func (uopq *UserOauthProviderQuery) First(ctx context.Context) (*UserOauthProvider, error) {
	nodes, err := uopq.Limit(1).All(setContextOp(ctx, uopq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{useroauthprovider.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uopq *UserOauthProviderQuery) FirstX(ctx context.Context) *UserOauthProvider {
	node, err := uopq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserOauthProvider ID from the query.
// Returns a *NotFoundError when no UserOauthProvider ID was found.
func (uopq *UserOauthProviderQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = uopq.Limit(1).IDs(setContextOp(ctx, uopq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{useroauthprovider.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uopq *UserOauthProviderQuery) FirstIDX(ctx context.Context) int64 {
	id, err := uopq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserOauthProvider entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserOauthProvider entity is found.
// Returns a *NotFoundError when no UserOauthProvider entities are found.
func (uopq *UserOauthProviderQuery) Only(ctx context.Context) (*UserOauthProvider, error) {
	nodes, err := uopq.Limit(2).All(setContextOp(ctx, uopq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{useroauthprovider.Label}
	default:
		return nil, &NotSingularError{useroauthprovider.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uopq *UserOauthProviderQuery) OnlyX(ctx context.Context) *UserOauthProvider {
	node, err := uopq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserOauthProvider ID in the query.
// Returns a *NotSingularError when more than one UserOauthProvider ID is found.
// Returns a *NotFoundError when no entities are found.
func (uopq *UserOauthProviderQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = uopq.Limit(2).IDs(setContextOp(ctx, uopq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{useroauthprovider.Label}
	default:
		err = &NotSingularError{useroauthprovider.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uopq *UserOauthProviderQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := uopq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserOauthProviders.
func (uopq *UserOauthProviderQuery) All(ctx context.Context) ([]*UserOauthProvider, error) {
	ctx = setContextOp(ctx, uopq.ctx, "All")
	if err := uopq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserOauthProvider, *UserOauthProviderQuery]()
	return withInterceptors[[]*UserOauthProvider](ctx, uopq, qr, uopq.inters)
}

// AllX is like All, but panics if an error occurs.
func (uopq *UserOauthProviderQuery) AllX(ctx context.Context) []*UserOauthProvider {
	nodes, err := uopq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserOauthProvider IDs.
func (uopq *UserOauthProviderQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if uopq.ctx.Unique == nil && uopq.path != nil {
		uopq.Unique(true)
	}
	ctx = setContextOp(ctx, uopq.ctx, "IDs")
	if err = uopq.Select(useroauthprovider.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uopq *UserOauthProviderQuery) IDsX(ctx context.Context) []int64 {
	ids, err := uopq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uopq *UserOauthProviderQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, uopq.ctx, "Count")
	if err := uopq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, uopq, querierCount[*UserOauthProviderQuery](), uopq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (uopq *UserOauthProviderQuery) CountX(ctx context.Context) int {
	count, err := uopq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uopq *UserOauthProviderQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, uopq.ctx, "Exist")
	switch _, err := uopq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (uopq *UserOauthProviderQuery) ExistX(ctx context.Context) bool {
	exist, err := uopq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserOauthProviderQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uopq *UserOauthProviderQuery) Clone() *UserOauthProviderQuery {
	if uopq == nil {
		return nil
	}
	return &UserOauthProviderQuery{
		config:     uopq.config,
		ctx:        uopq.ctx.Clone(),
		order:      append([]useroauthprovider.OrderOption{}, uopq.order...),
		inters:     append([]Interceptor{}, uopq.inters...),
		predicates: append([]predicate.UserOauthProvider{}, uopq.predicates...),
		// clone intermediate query.
		sql:  uopq.sql.Clone(),
		path: uopq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int64 `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserOauthProvider.Query().
//		GroupBy(useroauthprovider.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (uopq *UserOauthProviderQuery) GroupBy(field string, fields ...string) *UserOauthProviderGroupBy {
	uopq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserOauthProviderGroupBy{build: uopq}
	grbuild.flds = &uopq.ctx.Fields
	grbuild.label = useroauthprovider.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int64 `json:"user_id,omitempty"`
//	}
//
//	client.UserOauthProvider.Query().
//		Select(useroauthprovider.FieldUserID).
//		Scan(ctx, &v)
func (uopq *UserOauthProviderQuery) Select(fields ...string) *UserOauthProviderSelect {
	uopq.ctx.Fields = append(uopq.ctx.Fields, fields...)
	sbuild := &UserOauthProviderSelect{UserOauthProviderQuery: uopq}
	sbuild.label = useroauthprovider.Label
	sbuild.flds, sbuild.scan = &uopq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserOauthProviderSelect configured with the given aggregations.
func (uopq *UserOauthProviderQuery) Aggregate(fns ...AggregateFunc) *UserOauthProviderSelect {
	return uopq.Select().Aggregate(fns...)
}

func (uopq *UserOauthProviderQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range uopq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, uopq); err != nil {
				return err
			}
		}
	}
	for _, f := range uopq.ctx.Fields {
		if !useroauthprovider.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uopq.path != nil {
		prev, err := uopq.path(ctx)
		if err != nil {
			return err
		}
		uopq.sql = prev
	}
	return nil
}

func (uopq *UserOauthProviderQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserOauthProvider, error) {
	var (
		nodes = []*UserOauthProvider{}
		_spec = uopq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserOauthProvider).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserOauthProvider{config: uopq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, uopq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (uopq *UserOauthProviderQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uopq.querySpec()
	_spec.Node.Columns = uopq.ctx.Fields
	if len(uopq.ctx.Fields) > 0 {
		_spec.Unique = uopq.ctx.Unique != nil && *uopq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, uopq.driver, _spec)
}

func (uopq *UserOauthProviderQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(useroauthprovider.Table, useroauthprovider.Columns, sqlgraph.NewFieldSpec(useroauthprovider.FieldID, field.TypeInt64))
	_spec.From = uopq.sql
	if unique := uopq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if uopq.path != nil {
		_spec.Unique = true
	}
	if fields := uopq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useroauthprovider.FieldID)
		for i := range fields {
			if fields[i] != useroauthprovider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := uopq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uopq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uopq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uopq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uopq *UserOauthProviderQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uopq.driver.Dialect())
	t1 := builder.Table(useroauthprovider.Table)
	columns := uopq.ctx.Fields
	if len(columns) == 0 {
		columns = useroauthprovider.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uopq.sql != nil {
		selector = uopq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uopq.ctx.Unique != nil && *uopq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range uopq.predicates {
		p(selector)
	}
	for _, p := range uopq.order {
		p(selector)
	}
	if offset := uopq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uopq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserOauthProviderGroupBy is the group-by builder for UserOauthProvider entities.
type UserOauthProviderGroupBy struct {
	selector
	build *UserOauthProviderQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uopgb *UserOauthProviderGroupBy) Aggregate(fns ...AggregateFunc) *UserOauthProviderGroupBy {
	uopgb.fns = append(uopgb.fns, fns...)
	return uopgb
}

// Scan applies the selector query and scans the result into the given value.
func (uopgb *UserOauthProviderGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uopgb.build.ctx, "GroupBy")
	if err := uopgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserOauthProviderQuery, *UserOauthProviderGroupBy](ctx, uopgb.build, uopgb, uopgb.build.inters, v)
}

func (uopgb *UserOauthProviderGroupBy) sqlScan(ctx context.Context, root *UserOauthProviderQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(uopgb.fns))
	for _, fn := range uopgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*uopgb.flds)+len(uopgb.fns))
		for _, f := range *uopgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*uopgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uopgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserOauthProviderSelect is the builder for selecting fields of UserOauthProvider entities.
type UserOauthProviderSelect struct {
	*UserOauthProviderQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (uops *UserOauthProviderSelect) Aggregate(fns ...AggregateFunc) *UserOauthProviderSelect {
	uops.fns = append(uops.fns, fns...)
	return uops
}

// Scan applies the selector query and scans the result into the given value.
func (uops *UserOauthProviderSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uops.ctx, "Select")
	if err := uops.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserOauthProviderQuery, *UserOauthProviderSelect](ctx, uops.UserOauthProviderQuery, uops, uops.inters, v)
}

func (uops *UserOauthProviderSelect) sqlScan(ctx context.Context, root *UserOauthProviderQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(uops.fns))
	for _, fn := range uops.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*uops.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uops.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
